# ================================================================
# 파일명       : namespace.yaml
# 목적         : Linkdo 프로젝트 전용 네임스페이스
# ================================================================

apiVersion: v1
kind: Namespace
metadata:
  name: linkdo



